iiwa:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500  # in Hz

  # Controllers ------------------------------------------------
  TorqueController:
    type: effort_controllers/JointGroupEffortController
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

  # Controllers ------------------------------------------------
  PositionController:
    type: position_controllers/JointGroupPositionController
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6